Support MantleBackupConfig
cybozu-go/mantle pull request #11
Opened 2024-06-12 03:01 UTC by ushitora-anqou

2024-06-26 06:45 UTC, satoru-takeuchi commented
@ushitora-anqou Could you add `signed-off-by` in the 2nd and the 3rd commits?

2024-06-26 07:11 UTC, ushitora-anqou commented
> @ushitora-anqou Could you add `signed-off-by` in the 2nd and the 3rd commits?

I'll fix it later. That being said, we may need to introduce [DCO GitHub App](https://github.com/apps/dco) here, like TopoLVM.

2024-06-27 00:17 UTC, satoru-takeuchi requested changes

2024-06-27 00:17 UTC, satoru-takeuchi commented on internal/controller/mantlebackupconfig_controller.go
> +	runningPod, err := getRunningPod(ctx, r.Client)
```suggestion
	cronJobInfo, err := getCronJobInfo(ctx, r.Client)
```

How about remaning the function to exlain the role of this function clearly? In addition, it's better to define the dedicated struct for cronJobInfo because this informatino is not about the controller's pod itself. The new struct would be like this.

```
struct cronJobInfo {
  Namespace
  ServiceAccountName
  Image
}
```
  
```

2024-06-27 00:17 UTC, satoru-takeuchi commented on internal/controller/mantlebackupconfig_controller.go
> +		logger.Info("mbc not managed", "name", req.Name, "namespace", req.Namespace, "error", err)
```suggestion
		logger.Info("the target pvc is not managed by this controller", "name", req.Name, "namespace", req.Namespace, "error", err)
```

2024-06-27 00:17 UTC, satoru-takeuchi commented
@ushitora-anqou I didn't check test code since they will be changed after reflecting my comments.

2024-06-27 00:53 UTC, ushitora-anqou commented on cmd/backupandrotate/main.go
> +	_, _ = io.WriteString(hasher, name+"\000"+jobID)
Yes, it is. I adapted this code from pie: https://github.com/topolvm/pie/blob/cccc9bed6ed70bf6ed7ea042cac194de4ae0a5ba/internal/controller/pie/pieprobe_controller.go#L265

2024-06-27 01:15 UTC, ushitora-anqou commented on internal/controller/mantlebackupconfig_controller.go
> +	runningPod, err := getRunningPod(ctx, r.Client)
I mostly agree with you. We should probably define two separate functions: `getCronJobInfo` and `getRunningPod`. Then, `getCronJobInfo` can call `getRunningPod`. This way, `getRunningPod` can be reused for other purposes, even though it's currently only used for creating CronJobs.

2024-06-28 02:37 UTC, satoru-takeuchi requested changes

2024-06-28 02:37 UTC, satoru-takeuchi commented on internal/controller/mantlebackupconfig_controller_test.go
> +// cf. https://zenn.dev/nobishii/articles/type_param_intro_2#%E5%85%AC%E5%BC%8F%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AB%E8%A6%8B%E3%82%8B%E5%88%B6%E7%B4%84%E5%9E%8B%E6%8E%A8%E8
Could you replace this article with another one writtein in English, if possible?

2024-06-28 02:37 UTC, satoru-takeuchi commented on internal/controller/mantlebackupconfig_controller_test.go
> +		Entry("various expires 1", "0 0 * * *", "1d"),
```suggestion
		Entry("various expires 1", "0 0 * * *", "1d"),
```
```suggestion
		Entry("various expires 2", "0 0 * * *", "1d"),
```

Subsequent 1st argus should also be updated.

2024-06-28 02:37 UTC, satoru-takeuchi commented on test/e2e/backup_test.go
> +		Expect(err).NotTo(HaveOccurred())
It's not necessary to check errors here because it's  a teardown code. The new code will be like [this](https://github.com/cybozu-go/mantle/blob/aa8e4fac31644e3643029a76033f56095b345561/test/e2e/backup_test.go#L117-L134).

2024-06-28 02:37 UTC, satoru-takeuchi commented on test/e2e/backup_test.go
> +		By("Creating a Job from the CronJob")
It it to emulating the cretion of Job by CronJob and we don't wait for one day in this test? If so, describing it in L296 is better. Or can we introduce another command line parameter for test (like expireOffset)?

2024-06-28 02:37 UTC, satoru-takeuchi commented on test/e2e/testdata/values-mantle.yaml
> +  expireOffset: 100d
Can we emulate the actual behavior by changing expireOffset to several seconds or decent secods like '2w-10s'?

2024-06-28 04:34 UTC, ushitora-anqou commented on test/e2e/testdata/values-mantle.yaml
> +  expireOffset: 100d
I'm worried that we can't predict how quickly the MantleBackup resource will be deleted after it's created. For instance, if we set `expireOffset` to `1w6d59m50s` (i.e., 2w-10s), the deletion needs to happen at least 10 seconds after the creation is complete. If it happens any sooner, the test will fail. This makes the test flakier.

Maybe we can add a short delay in the test to ensure that the 10 seconds have passed. This might be a better approach. I'll give it a try and see how it works.

2024-06-28 04:36 UTC, satoru-takeuchi commented on test/e2e/testdata/values-mantle.yaml
> +  expireOffset: 100d
Indeed, please keep this code as is.

2024-06-28 04:38 UTC, ushitora-anqou commented on test/e2e/backup_test.go
> +		By("Creating a Job from the CronJob")
> It it to emulating the cretion of Job by CronJob and we don't wait for one day in this test? If so, describing it in L296 is better.

Yes, it is. I should have added some comments on it.

> Or can we introduce another command line parameter for test (like expireOffset)?

That sounds better. I'll fix the test that way.

2024-06-28 05:55 UTC, ushitora-anqou commented on test/e2e/testdata/values-mantle.yaml
> +  expireOffset: 100d
Well, after my fix for [your previous feedback](https://github.com/cybozu-go/mantle/pull/11#discussion_r1658058545), backup-and-rotate subcommand will be triggered every 60 seconds, so we can safely use `1w6d59m50s`.

2024-06-28 08:05 UTC, ushitora-anqou commented on test/e2e/backup_test.go
> +		By("Creating a Job from the CronJob")
Instead of `scheduleOffset`, I introduced `overwrite-mbc-schedule` option. When we use this option with some value (e.g., `* * * * *`), every .spec.schedule of a CronJob created for a MBC is replaced with the value. We can set this to `* * * * *` for the e2e test. Then, the backup-and-rotate subcommand will be triggered every minute.

2024-07-09 02:30 UTC, satoru-takeuchi approved these changes
@ushitora-anqou LGTM. Please squash your commits.

2024-07-09 04:52 UTC, merged