use kvm2 driver for minikube
cybozu-go/mantle pull request #22
Opened 2024-06-25 01:16 UTC by peng225

I setup the e2e test to use kvm2 driver for minikube.

2024-06-25 09:03 UTC, ushitora-anqou requested changes

2024-06-26 04:44 UTC, peng225 commented on test/e2e/Makefile
> +	$(MINIKUBE) ssh -- $(SUDO) $(LOSETUP) $(LOOP_DEV2) $(LOOP_FILE2)
Thanks! I fixed it.

> I believe the two dd won't override the loop files because they use seek.

I agree with you.

2024-06-26 04:45 UTC, peng225 commented on test/e2e/Makefile
>  delete-minikube:
Fixed.

2024-06-26 04:45 UTC, peng225 commented on test/e2e/Makefile
>  	$(SUDO) -E env \
Fixed.

2024-06-26 04:57 UTC, ushitora-anqou commented
LGTM. I'll approve this PR after the CI pass.

2024-06-26 06:35 UTC, ushitora-anqou approved these changes

2024-06-26 06:35 UTC, merged