Implement multi Rook/Ceph env e2e
cybozu-go/mantle pull request #27
Opened 2024-06-26 09:30 UTC by llamerada-jp

2024-07-03 00:45 UTC, satoru-takeuchi requested changes

2024-07-03 00:45 UTC, satoru-takeuchi commented on test/e2e/multi_rook_ceph_test.go
> +	It("describing the test environment", func() {
```suggestion
	It("setting up the test environment", func() {
```

2024-07-03 00:45 UTC, satoru-takeuchi commented on test/e2e/multi_rook_ceph_test.go
> +	mantleRestoreName string // use the same restore name for both tenants
```suggestion
	mantleBackupName  string // use the same MantleBackup name for both tenants
	mantleRestoreName string // use the same MantleRestore name for both tenants
```

2024-07-03 00:45 UTC, satoru-takeuchi commented on test/e2e/backup_test.go
>  		}
How about deleting RBD images in the second RBD images as the old code did? It's the teardown logic and it should cleanup the environment as possible.

2024-07-03 00:45 UTC, satoru-takeuchi commented on test/e2e/multi_rook_ceph_test.go
> +	}
How about deleting RBD images in the second cluster [as the old code did](https://github.com/cybozu-go/mantle/pull/27/files#diff-c1cddc33537f5a0b043fc5b2e1c38f347f6e95ca915fce01b853c2fbc473a825L105-L115)? It's the teardown logic and it should cleanup the environment as possible.

2024-07-03 00:45 UTC, satoru-takeuchi commented on test/e2e/multi_rook_ceph_test.go
> +	It("create PVC, backup, and restore in tenant namespace 1", func() {
```suggestion
	It("create PVC, backup, and restore in the tenant namespace 1", func() {
```

2024-07-03 00:45 UTC, satoru-takeuchi commented on test/e2e/util.go
> +func seekImageAndSnapNames(namespace, pool string) ([]string, error) {
```suggestion
func getImageAndSnapNames(namespace, pool string) ([]string, error) {
```

`get` is more appropriate word.

2024-07-03 00:45 UTC, satoru-takeuchi commented on test/e2e/multi_rook_ceph_test.go
> +		Expect(imageAndSnaps1).To(HaveLen(3))
This code strongly depends on the output format of json. How about change the return values of  `seekImageAndSnapNames` to (string, []string, err)? The first return value just returns the name of image. The second string just contains the array of snapshot names. I consider we can do it by removing `--format=json` from `rbd ls` and `rbd snap ls`.

2024-07-04 04:17 UTC, llamerada-jp commented on test/e2e/backup_test.go
>  		}
Tests using cephCluster2Namespace are moved to `mult_rook_ceph_test.go` and RBD images are removed in `clean up the dummy data` section.

2024-07-04 06:03 UTC, satoru-takeuchi commented on test/e2e/backup_test.go
>  		}
OK, I see.

2024-07-04 08:22 UTC, llamerada-jp commented on test/e2e/multi_rook_ceph_test.go
> +		Expect(imageAndSnaps1).To(HaveLen(3))
Your idea could only return one rbd image, in fact, there can be more than one. I considered using a map or struct, but I chose a slice as a return value, which is easy to compare with `ConsistOf`. 
Some implementations on `internal/ceph/ceph.go` and `internal/controller/*_controller.go` are already depending on the format of rbd command. Our code will depend on the text format of rbd command instead of JSON format if we avoid using JSON format output. I hope you accept to use JSON format outputs from rbd command.

2024-07-04 08:25 UTC, satoru-takeuchi commented on test/e2e/multi_rook_ceph_test.go
> +		Expect(imageAndSnaps1).To(HaveLen(3))
OK. Could you use consts or variables rather than literals("3" or "6") instead?

2024-07-04 08:41 UTC, llamerada-jp commented on test/e2e/multi_rook_ceph_test.go
> +		Expect(imageAndSnaps1).To(HaveLen(3))
According to [the official document](https://pkg.go.dev/github.com/onsi/gomega#ConsistOf), `ConsistOf` checks the length of slice. So, I will remove the checks of the length.

> ConsistOf succeeds if actual contains precisely the elements passed into the matcher.

2024-07-08 00:30 UTC, satoru-takeuchi requested changes

2024-07-08 00:30 UTC, satoru-takeuchi commented on test/e2e/util.go
> +	// remove RBD snapshots first
It's better to mention RBD clone images.

```suggestion
	// remove RBD clone images of targets, RBD anspshots of targets, and target images in order
	// to remove them cleanly. 
```

2024-07-08 00:30 UTC, satoru-takeuchi commented on test/e2e/multi_rook_ceph_test.go
> +			Expect(err).NotTo(HaveOccurred())
It's better to continue the teardown even if some deletion failed not to restore clean environment as possible.

```suggestion
		It("delete resources in the namespace: "+ns, func() {
			err := deleteNamespacedResource(ns, "mantlerestore")
			err = deleteNamespacedResource(ns, "mantlebackup")
			err = deleteNamespacedResource(ns, "pvc")
		})

		It("delete the namespace: "+ns, func() {
			_, stderr, err := kubectl("delete", "namespace", ns)
		})
	}

	It("clean up the SCs and RBD pools", func() {
		for _, sc := range []string{test.storageClassName1, test.storageClassName2} {
			_, stderr, err := kubectl("delete", "sc", sc)
		}

		for _, ns := range []string{cephCluster1Namespace, cephCluster2Namespace} {
			err := removeAllRBDImageAndSnap(ns, test.poolName)

			_, _, err = kubectl("delete", "-n", ns, "cephblockpool", test.poolName, "--wait=false")
```

2024-07-08 00:30 UTC, satoru-takeuchi commented on test/e2e/restore_test.go
> +		Expect(err).NotTo(HaveOccurred())
Same as multi_rook_ceph_test.go#tearDownEnv().

2024-07-08 00:31 UTC, satoru-takeuchi commented
@llamerada-jp This PR will be merged after my last minor change requests.

2024-07-08 01:28 UTC, llamerada-jp commented on test/e2e/multi_rook_ceph_test.go
> +			Expect(err).NotTo(HaveOccurred())
I would like to leave these because the errors raised by tearDown sometimes made me notice cases that I was not noticed. Of course, if you know it will be an error, then it's not.

2024-07-08 01:29 UTC, satoru-takeuchi commented on test/e2e/multi_rook_ceph_test.go
> +			Expect(err).NotTo(HaveOccurred())
OK, I understood.

2024-07-08 01:29 UTC, satoru-takeuchi commented on test/e2e/restore_test.go
> +		Expect(err).NotTo(HaveOccurred())
It's also OK not to fix.

2024-07-08 02:28 UTC, satoru-takeuchi approved these changes

2024-07-08 02:28 UTC, merged