Change expire strategy
cybozu-go/mantle pull request #39
Opened 2024-09-18 10:14 UTC by toshipp

2024-10-09 09:58 UTC, satoru-takeuchi requested changes

2024-10-09 09:58 UTC, satoru-takeuchi commented on internal/ceph/util.go
> +func FindRBDSnapshot(cmd CephCmd, pool, image, snap string) (*RBDSnapshot, error) {
ditto. The definition of this function is a bit odd. Although this function is to find a snapshot that matches the conditions defined in arguments, there is an argument named `snap`. I prefer `IsRBDSnapshotNamed(name)` than `IsRBDSnapshotNamed(snap)`.

2024-10-09 09:58 UTC, satoru-takeuchi commented on internal/controller/internal/testutil/fake_rbd.go
> +	f.lastSnapId++
This code implies we can't have a snapshot that id is 0 although the id of the first snapshot is 0 in Ceph. How about renaming `lastSnapId` to `nextSnapId` and moving this code after L57?

2024-10-09 09:58 UTC, satoru-takeuchi commented on internal/controller/internal/testutil/fake_rbd_test.go
> +		Expect(err).To(HaveOccurred())
Could you also check `RBDSnapLs` returns only `snap2` here?

2024-10-09 10:04 UTC, satoru-takeuchi commented
@toshipp Although I'm in the middle of review, I left some comments about the first commit to "CephCmd in mantlebackup_controller".

2024-10-10 07:17 UTC, toshipp commented on internal/ceph/ceph.go
> +type RBDSnapshot struct {
will do.

2024-10-10 07:22 UTC, toshipp commented on internal/ceph/ceph.go
> +type RBDSnapshot struct {
https://github.com/cybozu-go/mantle/blob/4120d3817a01986695634ae8a7a2fe5984236821/test/e2e/singlek8s/util.go#L188
I found it is used. However, this can be removed by using ceph package.

2024-10-10 07:38 UTC, toshipp commented on internal/ceph/util.go
> +func IsRBDSnapshotNamed(snap string) func(RBDSnapshot) bool {
lgtm

2024-10-10 07:50 UTC, toshipp commented on internal/ceph/util.go
> +func FindRBDSnapshot(cmd CephCmd, pool, image, snap string) (*RBDSnapshot, error) {
I can't entirely agree with your idea. There are many names, pool name, image name, and snapshot name. I assume using snap is more readable to refer the snapshot name.

2024-10-10 07:51 UTC, toshipp commented on internal/controller/internal/testutil/fake_rbd.go
> +	f.lastSnapId++
will do

2024-10-10 07:54 UTC, toshipp commented on internal/controller/internal/testutil/fake_rbd_test.go
> +		Expect(err).To(HaveOccurred())
will do

2024-10-10 08:15 UTC, toshipp commented on internal/controller/mantlebackup_controller_test.go
> +			backup.Spec.Expire = "1d"
I considered explicitly specifying the value makes the test more stable. If someone changes the default to 2d in testutil, this test will fail. But adding some duration to the previous value is more readable, IMO, I'll update this.

2024-10-10 08:45 UTC, satoru-takeuchi commented
@toshipp Please resolve conflicts caused by merging the last PR.

2024-10-10 08:53 UTC, toshipp commented
@satoru-takeuchi 
I'm thinking of rebasing it after the review is done. There are many conflicts, I think it is hard to review this if rebasing is done during the review.

2024-10-10 09:09 UTC, satoru-takeuchi approved these changes
LGTM. Please rebase it to main.

2024-10-10 10:36 UTC, toshipp commented
@satoru-takeuchi 
Rebased. Please check if I did something wrong.

2024-10-10 23:43 UTC, merged