fix MantleBackup's reconciler for data replication
cybozu-go/mantle pull request #41
Opened 2024-09-20 04:31 UTC by ushitora-anqou

2024-09-20 09:57 UTC, satoru-takeuchi requested changes

2024-09-20 09:57 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller.go
> +				!meta.IsStatusConditionTrue(backup1.Status.Conditions, mantlev1.BackupConditionSyncedToRemote) {
The condition is OK. However, this situation is not an error like the failure of access to API servers but waiting for fullfilling some conditions. So, it's better to return from `Reconcile()`  with `ctrl.Result{Requeue: true}, nil`. Probably the return value of `replicate()` should also be changed to distinguish whether the request will be requeued due to error or not.

I should be noticed this point in the previous PR which is to implementing `replicate()`. My fault.

2024-09-24 01:12 UTC, toshipp commented on internal/controller/mantlebackup_controller.go
> +		}
Writing logic in Reconcile method makes it hard to read and maintain, IMO.
I'd like to embed it into replicate method as a precondition check or split it as a function.

2024-09-24 03:08 UTC, ushitora-anqou commented
@satoru-takeuchi @toshipp I fixed my code according to your reviews. Could you review this PR again? The changes are as follows: https://github.com/cybozu-go/mantle/compare/6d291c37d39095bca8d6a54db12329b5bd67aa63..a5039dd0cda8ae26cea5ce2343926c5881b49b0c

2024-09-24 03:14 UTC, toshipp commented on internal/controller/mantlebackup_controller.go
> +		if err := r.replicate(ctx, logger, &backup); err == errSkipProcessing {
My intent of errSkipProcessing is to finish reconciling the MB without requeue. If you want requeue, why don't you return ctrl.Result from replicate method?

2024-09-24 08:41 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		if err := r.replicate(ctx, logger, &backup); err == errSkipProcessing {
I fixed my code. Could you take another look at it to make sure it's what you had in mind?

2024-09-24 09:19 UTC, toshipp reviewed
lgtm

2024-09-24 22:25 UTC, satoru-takeuchi approved these changes

2024-09-24 22:25 UTC, merged

2024-09-25 00:33 UTC, ushitora-anqou commented
Thank you!