check MB labels before any other write operations
cybozu-go/mantle pull request #46
Opened 2024-10-03 02:33 UTC by ushitora-anqou

issue: cybozu-private/csa-apps#3011
Signed-off-by: Ryotaro Banno <ryotaro.banno@gmail.com>

2024-10-04 10:06 UTC, satoru-takeuchi requested changes

2024-10-08 02:04 UTC, ushitora-anqou commented
Note: I need to change the commit messages of some commits to reflect their fixed contents.

2024-10-08 02:27 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		prepare, result, err := r.prepareForDataSynchronization(ctx, &backup, r.primarySettings.Client)
I couldn't come up with anything good. I'll use `prepareResult`.

2024-10-08 02:37 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	// Make sure that the reconciled MantleBackup is created not by the secondary mantle but by the primary mantle.
fixed in https://github.com/cybozu-go/mantle/pull/46/commits/c501f70ca1d62f3d89fc54834bd31d1d3accadf7

2024-10-08 02:37 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +func validateMantleBackupAsPrimary(backup *mantlev1.MantleBackup) error {
fixed in https://github.com/cybozu-go/mantle/pull/46/commits/c501f70ca1d62f3d89fc54834bd31d1d3accadf7

2024-10-08 02:37 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +func (r *MantleBackupReconciler) removeFinalizerAndRBDSnapshot(
fixed in https://github.com/cybozu-go/mantle/pull/46/commits/00cae6d19e7242d59c82ce4e1e371612ed6faed7

2024-10-08 02:39 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		if _, ok := backup.GetAnnotations()[annotDiffTo]; ok {
fixed in https://github.com/cybozu-go/mantle/pull/46/commits/851b98f0bad03cbf65c7df4de0492dbe563d124d and https://github.com/cybozu-go/mantle/pull/46/commits/b9e49ce3002e33471633239e9481d216de905b9a

2024-10-08 02:39 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		return r.export(ctx, &backup, r.primarySettings.Client, prepare)
fixed in https://github.com/cybozu-go/mantle/pull/46/commits/8a87df319ee6eca9420ac5efd359cc6f7d3ec3b7

2024-10-08 02:39 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	diffFrom                          *mantlev1.MantleBackup // non-nil value iff isFull is false.
fixed in https://github.com/cybozu-go/mantle/pull/46/commits/ae497fdcb49dda27149ab817956a0f839e688ce0

2024-10-08 02:40 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		prepare, result, err := r.prepareForDataSynchronization(ctx, &backup, r.primarySettings.Client)
fixed in https://github.com/cybozu-go/mantle/pull/46/commits/21c9c54af018f0742760731e688f0dd3ab69c732

2024-10-08 02:51 UTC, ushitora-anqou commented
@satoru-takeuchi I think I've fixed all the issues you mentioned. Could you review this PR again?

Note that I need to squash my fixup commits, so please don't merge it yet, even if the code looks good to you.

2024-10-08 05:32 UTC, ushitora-anqou commented
@satoru-takeuchi I think I've fixed all the issues you mentioned. Could you review this PR again?

Note that I need to squash my fixup commits, so please don't merge it yet, even if the code looks good to you.

2024-10-09 00:13 UTC, satoru-takeuchi approved these changes
LGTM. Please squash commits.

2024-10-09 02:39 UTC, ushitora-anqou commented
Note: comparison: https://github.com/cybozu-go/mantle/compare/2e874d56d3467a52149d3755b4b2d2b3fe33c910..416bad5ccca987c47dfbca4148f62ebf1db2d598

2024-10-09 03:35 UTC, merged