implement prepareForDataSynchronization func
cybozu-go/mantle pull request #51
Opened 2024-10-09 09:18 UTC by peng225

Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>

2024-10-16 00:25 UTC, satoru-takeuchi requested changes
@peng225 I've reviewed only implementation code and have not reviewed test code yet. I'll provide the remaining feedback later.

2024-10-16 00:25 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller.go
> +	candidates := make([]*mantlev1.MantleBackup, 0)
How about removing `candidates` and insert `var candidate *mantlev1.MantleBackup; candidate := nil` in L721? Then we can replace L738 with the following snippet.

```go
if candidate != nil || *caididate.Status.SnapID < *primaryBackup.Status.SnapID {
  candidate := primaryBackup
}
```

In addition, we can remove the sort process in L744-L746.

2024-10-16 05:17 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	prepareResult, err := r.prepareForDataSynchronization(ctx, backup, r.primarySettings.Client)
> This result is to describe the next action of reconciler (continue, requeue (after some duration) with/without errors).

I understand your concern.

The reason why I removed `result` is because the linter complained about it.
In fact, if I restore `result` `prepareForDataSynchronization` always return the same value for `result`.

Perhaps, I don't correctly understand the case where we should return non-empty result.

Another option is just returning the empty result at L408.

2024-10-16 05:22 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +		primaryBackup := primaryBackup
That is to resolve the lint error.

2024-10-16 05:29 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	)
> How about declaring `isIncremental`

Sorry, but I couldn't understand where to define it, and what `isIncremental` is. Is it a bool-typed variable? or something else? 

> diffFrom fields in `dataSyncPrepareResult` is undefined if `isSecondaryMantleBackupReadyToUse` is true? Then we can return here if `isSecondaryMantleBackupReadyToUse` is true.

If letting `diffFrom` be nil is acceptable in this case, I can change the code.

2024-10-16 07:40 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	)
I understand your point.
Though we need to change the spec, I can try to change the code as you proposed.

2024-10-16 08:19 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	exportTargetPVCUID := backup.GetLabels()[labelLocalBackupTargetPVCUID]
Fixed.
https://github.com/cybozu-go/mantle/pull/51/commits/6ef1a3ca50f54d2daf392f50533660e7abc1ab9e

2024-10-16 08:19 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	secondaryBackupSet := convertToMap(secondaryBackups)
Fixed.
https://github.com/cybozu-go/mantle/pull/51/commits/6ef1a3ca50f54d2daf392f50533660e7abc1ab9e

2024-10-16 08:25 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	candidates := make([]*mantlev1.MantleBackup, 0)
Thank you for your suggestion.
Perhaps, `if candidate != nil` should be `if candidate == nil`.
I changed the code.
https://github.com/cybozu-go/mantle/pull/51/commits/6ef1a3ca50f54d2daf392f50533660e7abc1ab9e

I also changed the variable name to `diffOrigin` because that is no longer the candidate, but the result itself.

2024-10-16 15:04 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	diffFrom                          *mantlev1.MantleBackup // non-nil value iff isIncremental is true and isSecondaryMantleBackupReadyToUse is false.
These comments are wrong. I will fix it.

2024-10-17 06:34 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller.go
> +	prepareResult, err := r.prepareForDataSynchronization(ctx, backup, r.primarySettings.Client)
> Another option is just returning the empty result at L408L407.

This idea looks good to me. Let's keep the current change as is and return the empty result at L407.

2024-10-17 08:25 UTC, satoru-takeuchi requested changes

2024-10-17 08:25 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +		"test2": basePrimaryBackups[1].DeepCopy(),
Could you tell me why `testSecondaryMantleBackups` includes "test2"? "test1", "test3", "test4", "test0", and "test2" are replicated in order [by design](https://github.com/cybozu-go/mantle/blob/c29344c01ebb7de446036e78a7ad4fc05c9d6cf3/internal/controller/mantlebackup_controller.go#L432-L439).

2024-10-17 08:25 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +		// "test4" is intentionally omitted.
Could you describe why it's ommited? Is it to emuate the case that "test4" was repliated but was deleted after that?

2024-10-18 00:36 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	prepareResult, err := r.prepareForDataSynchronization(ctx, backup, r.primarySettings.Client)
Fixed.
https://github.com/cybozu-go/mantle/pull/51/commits/bbb78d88890f3d3904e131f0b270476d45c0804e

2024-10-18 00:46 UTC, peng225 commented on internal/controller/mantlebackup_controller_test.go
> +		// "test4" is intentionally omitted.
> Is it to emuate the case that "test4" was repliated but was deleted after that?

Yes.

2024-10-18 00:56 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +		"test2": basePrimaryBackups[1].DeepCopy(),
@peng225 Sorry, I should have explained what I meant more clearly. My point was, "test2" mon't be existed in the secondary k8s cluster because its snapID is higher than the "test0"'s one.

2024-10-18 00:57 UTC, peng225 commented on internal/controller/mantlebackup_controller_test.go
> +		"test2": basePrimaryBackups[1].DeepCopy(),
I understand the design is as you explained.

I just believe that we should check every possible condition in the unit tests, even if those conditions are unlikly to occur when everything is functioning correctly.

This is just my personal opinion. I can also remove such unlikely test cases. Which do you think is better?

2024-10-18 01:00 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +		"test2": basePrimaryBackups[1].DeepCopy(),
I understood. It's not necessary to remove the test code. Instead, could you add a comment to the purpose of the existence of "test2" in the secondary cluster?

2024-10-18 01:08 UTC, peng225 commented on internal/controller/mantlebackup_controller_test.go
> +		"test2": basePrimaryBackups[1].DeepCopy(),
@satoru-takeuchi 
Sorry, but I reconcidered it, and have changed my mind.
I misunderstood that the exsistence of "test2" on the second cluster contributed to the higher test coverrage, but I realised it did not.

Let me remove "test2" on the second cluster, 
("test2" should be in the primary cluster to check if we can skip the MantleBackup with the higher snapID.)

2024-10-18 01:14 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +	secondaryBackupSet map[string]*mantlev1.MantleBackup,
Fixed.
https://github.com/cybozu-go/mantle/pull/51/commits/105292a8e63d23a28cbf929c0d52822fda448407

2024-10-18 01:15 UTC, peng225 commented on internal/controller/mantlebackup_controller.go
> +		secondaryBackup, ok := secondaryBackupSet[primaryBackup.Name]
Fixed.
https://github.com/cybozu-go/mantle/pull/51/commits/105292a8e63d23a28cbf929c0d52822fda448407

2024-10-18 01:15 UTC, peng225 commented on internal/controller/mantlebackup_controller_test.go
> +			secondaryBackupSet map[string]*mantlev1.MantleBackup,
Fixed.
https://github.com/cybozu-go/mantle/pull/51/commits/105292a8e63d23a28cbf929c0d52822fda448407

2024-10-18 01:16 UTC, peng225 commented on internal/controller/mantlebackup_controller_test.go
> +			foundBackup := searchForDiffOriginMantleBackup(backup, primaryBackups, secondaryBackupSet)
Fixed.
https://github.com/cybozu-go/mantle/pull/51/commits/105292a8e63d23a28cbf929c0d52822fda448407

2024-10-18 01:17 UTC, peng225 commented on internal/controller/mantlebackup_controller_test.go
> +		"test2": basePrimaryBackups[1].DeepCopy(),
> Let me remove "test2" on the second cluster,

I added a comment.
https://github.com/cybozu-go/mantle/pull/51/commits/8b3b868bcd45cd3ee49e2284919104657f6ca08c

2024-10-18 01:27 UTC, satoru-takeuchi approved these changes
@peng225 LGTM. Could you squash commits once CI passes?

2024-10-18 02:01 UTC, peng225 commented
@satoru-takeuchi 
I squashed commits. Could you check again?

2024-10-18 02:06 UTC, satoru-takeuchi approved these changes

2024-10-18 02:06 UTC, merged