add tests for prepareForDataSynchronization func
cybozu-go/mantle pull request #52
Opened 2024-10-18 08:06 UTC by peng225

Signed-off-by: Shinya Hayashi <shinya-hayashi@cybozu.co.jp>

2024-10-25 01:01 UTC, satoru-takeuchi requested changes

2024-10-28 01:35 UTC, peng225 commented on internal/controller/mantlebackup_controller_test.go
> +			shouldbeDeleted := false
Fixed.
https://github.com/cybozu-go/mantle/compare/422e9f9fd8c354bf96b67a9b80d8789737acf645..a0e5141623f5e8a82fbe426f28d81cba85aa0ed1

2024-10-28 01:35 UTC, peng225 commented on internal/controller/mantlebackup_controller_test.go
> +	testName := "test5"
Fixed.
https://github.com/cybozu-go/mantle/compare/422e9f9fd8c354bf96b67a9b80d8789737acf645..a0e5141623f5e8a82fbe426f28d81cba85aa0ed1

2024-10-28 03:44 UTC, satoru-takeuchi commented
Although `build` workflow failed, it seems not to be relatated to this PR. The test fails on creating minikube cluster. I re-ran this workflow.

2024-10-28 03:47 UTC, satoru-takeuchi approved these changes
@peng225 LGTM. Do you plan to squash commits? If else, I'll merge this PR after CI succeeded.

2024-10-28 04:03 UTC, peng225 commented
> Do you plan to squash commits?

No, I don't. Now that CI has passed, I'll merge it.

2024-10-28 04:03 UTC, merged