Implement export
cybozu-go/mantle pull request #54
Opened 2024-10-25 01:00 UTC by ushitora-anqou

2024-10-31 02:10 UTC, ushitora-anqou commented on internal/controller/replication.go
> +			&target,
```suggestion
			&source,
```

2024-11-01 10:24 UTC, satoru-takeuchi requested changes

2024-11-01 10:24 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller.go
> +# Replicate the script from toolbox.sh inline so the ceph image
Please add the URL points the Rook's source code to clarify we conform open source license.

2024-11-01 10:24 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller.go
> +	for _, cond := range job.Status.Conditions {
You can use [`IsStatusConditionPresentAndEqual()`](https://pkg.go.dev/k8s.io/apimachinery/pkg/api/meta#IsStatusConditionPresentAndEqual).

2024-11-01 10:24 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller.go
> +		labels["app.kubernetes.io/component"] = "upload-job"
Please add a constant for "upload-job".

2024-11-05 05:09 UTC, ushitora-anqou commented on internal/controller/internal/testutil/resources.go
> +func (r *ResourceManager) ChangeJobCondition(ctx context.Context, job *batchv1.Job, condType batchv1.JobConditionType, condStatus corev1.ConditionStatus) error {
I don't think we can use `meta.SetStatusCondition` here, because `meta.SetStatusCondition` accepts `metav1.Condition`, which is not interchangeable with the type of `job.Status.Conditions`, i.e., 
 `batchv1.JobCondition`.

2024-11-05 06:57 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	pvc.SetName(fmt.Sprintf("mantle-export-%s", target.GetUID()))
I think `makeExportPVCName` is used here. I've noticed that the implementation of `makeExportPVCName` is wrong and it should return `mantle-export-<PVC>` instead of `mantle-export-<namespace>-<name>`. I'll fix this.

2024-11-05 07:11 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	for _, cond := range job.Status.Conditions {
I don't think we can use `meta.IsStatusConditionPresentAndEqual` here because it accepts `[]metav1.Condition` but `job.Status.Conditions` has `[]JobCondition` type.

2024-11-05 07:14 UTC, ushitora-anqou commented on internal/controller/replication.go
> +			&target,
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/28b4cec881f4be040e6f3c9381f7b12333124da9

2024-11-05 07:15 UTC, ushitora-anqou commented on cmd/controller/main.go
> +	flags.StringVar(&caCertConfigMapSrc, "ca-cert-config-map", "",
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/b7bf4486c494d9c43fe9efa4517c1386318969e9

2024-11-05 07:15 UTC, ushitora-anqou commented on cmd/controller/main.go
> +		"The bucket name of the object storage which should be used in the backups.")
Fixed in ts/ff179321241fa05c98eaa4cdd885437f19db95e0

2024-11-05 07:15 UTC, ushitora-anqou commented on cmd/controller/main.go
> +		setupLog.Error(errors.New("POD_IMAGE is empty"), "POD_IMAGE is empty")
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/c43af70cce527b3c29c507da59fa9975a0cdb718

2024-11-05 07:15 UTC, ushitora-anqou commented on cmd/controller/main.go
> +		caCertConfigMap = &caCertConfigMapSrc
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/e4f1d6641c8ba65111aaf937369c97e1a0b8316d

2024-11-05 07:16 UTC, ushitora-anqou commented on internal/controller/replication.go
> +		return nil, errors.New("syncMode is invalid")
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/5d26babf02f37472921725741f916b89dbd463a7

2024-11-05 07:16 UTC, ushitora-anqou commented on internal/controller/replication.go
> +		(req.DiffFrom == nil || *req.DiffFrom != diffFrom) {
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/5d26babf02f37472921725741f916b89dbd463a7

2024-11-05 07:16 UTC, ushitora-anqou commented on cmd/controller/main.go
> +
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/fb13bf5c0caad95fa6a20c0010f28c9963543d86

2024-11-05 07:16 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	// FIXME: this is inserted only for tests and should be removed in the future.
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/0dce9ee4f2daaf3fac36bda9f21395b5029cff25

2024-11-05 07:16 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	if result, err := r.checkNumOfExportJobs(ctx); err != nil || !result.IsZero() {
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/3264d418ece20dcc85a007e995c7130a95e127ed

2024-11-05 07:17 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	if result, err := r.checkExportJobStatus(ctx, targetBackup); err != nil || !result.IsZero() {
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/ac103e0298a47f4d3b00cd76cb70b17e91dff740

2024-11-05 07:17 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	pvcSize.Mul(2)
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/1ebe78d7174b0436c2f4edb25a4983053e08920a.

2024-11-05 07:17 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +			"app.kubernetes.io/component": "export-job",
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/a6fc81ae6fb23abf295d36fdd806d6b95c396ccd.

2024-11-05 07:17 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		labels["app.kubernetes.io/component"] = "export-data"
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/a6fc81ae6fb23abf295d36fdd806d6b95c396ccd.

2024-11-05 07:18 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +	pvc.SetName(fmt.Sprintf("mantle-export-%s", target.GetUID()))
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/2280c50b76eb2dc2915894281f0a44b29e48ea6e.

2024-11-05 07:22 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +func makeExportPVCName(target *mantlev1.MantleBackup) string {
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/fceec145a64af91dda821d2f98bd5dba151a4cbf.

2024-11-05 07:22 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +# Replicate the script from toolbox.sh inline so the ceph image
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/3fe9129b6d3988f21040b9a5277fe5df99c7f163.

2024-11-05 07:22 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		labels["app.kubernetes.io/component"] = "upload-job"
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/3ca2e076da7cfd387e7f73402131f81eb59fd69a.

2024-11-05 07:30 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		pvc.Spec.StorageClassName = &r.primarySettings.ExportDataStorageClass
Fixed in https://github.com/cybozu-go/mantle/pull/54/commits/cc9b792df61f8067df9cb705132ccada9d8e7258.

2024-11-05 08:19 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller.go
> +		pvc.Spec.StorageClassName = &r.primarySettings.ExportDataStorageClass
After some struggle, I found that we can't make such owner references because the namespace of the Jobs and PVCs may be different from `target`.

2024-11-06 05:46 UTC, satoru-takeuchi approved these changes
LGTM. Please squash commits.

2024-11-06 06:50 UTC, ushitora-anqou commented
@satoru-takeuchi Thank you for your review. I squashed my commits.

2024-11-06 06:50 UTC, merged