Add tests for export
cybozu-go/mantle pull request #59
Opened 2024-10-31 02:39 UTC by ushitora-anqou

~~The commits included in this PR should be rebased after #54 is merged into the main branch.~~ done.

2024-11-07 07:30 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +				}
Could you also check the `FROM_SNAP_NAME` is defined in `Spec.Containers[0].Env`? The current code can't distinguish the following cases:

- (a) This envvar is not defined.
- (b) This envvar is defined and is empty.

2024-11-07 07:34 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +				}
ditto.

2024-11-07 07:45 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +			Expect(aerrors.IsNotFound(err)).To(BeTrue())
Please use `Consistently` here not to overlook the creation of upload job after #510.

2024-11-07 08:36 UTC, satoru-takeuchi requested changes
I completed to review this PR and left some additional minor suggestions.

2024-11-07 08:36 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +		isError bool,
```suggestion
		shouldBeError bool,
```

2024-11-07 08:36 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +			"a backup should fail if target's ReadToUse is True",
```suggestion
			"a backup should fail if target's ReadyToUse is True",
```

2024-11-07 08:36 UTC, satoru-takeuchi commented on internal/controller/mantlebackup_controller_test.go
> +		isError bool,
```suggestion
		shouldBeError bool,
```

2024-11-08 06:02 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller_test.go
> +		ns2 := resMgr.CreateNamespace()
Fixed in https://github.com/cybozu-go/mantle/pull/59/commits/7078d9890755fe72881e7618af2cbfec012b14f3.

2024-11-08 06:02 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller_test.go
> +		createAndExportMantleBackup(mbr2, "target2", ns2)
Fixed in https://github.com/cybozu-go/mantle/pull/59/commits/7078d9890755fe72881e7618af2cbfec012b14f3.

2024-11-08 06:03 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller_test.go
> +				}
Fixed in https://github.com/cybozu-go/mantle/pull/59/commits/aefbb65b37389ee148bac132588d9573da18af4a.

2024-11-08 06:03 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller_test.go
> +				}
Fixed in https://github.com/cybozu-go/mantle/pull/59/commits/aefbb65b37389ee148bac132588d9573da18af4a.

2024-11-08 06:03 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller_test.go
> +			Expect(aerrors.IsNotFound(err)).To(BeTrue())
Fixed in https://github.com/cybozu-go/mantle/pull/59/commits/c07278f10481efe9bcef0cca114a7b090f7b1380.

2024-11-08 06:03 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller_test.go
> +		isError bool,
Fixed in https://github.com/cybozu-go/mantle/pull/59/commits/2cde0591eb1b568fd990cc709bd7619822853972.

2024-11-08 06:03 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller_test.go
> +			"a backup should fail if target's ReadToUse is True",
Fixed in https://github.com/cybozu-go/mantle/pull/59/commits/2cde0591eb1b568fd990cc709bd7619822853972.

2024-11-08 06:03 UTC, ushitora-anqou commented on internal/controller/mantlebackup_controller_test.go
> +		isError bool,
Fixed in https://github.com/cybozu-go/mantle/pull/59/commits/2cde0591eb1b568fd990cc709bd7619822853972.

2024-11-08 06:04 UTC, ushitora-anqou commented
@satoru-takeuchi I fixed you points. Could you review this again?

2024-11-08 06:10 UTC, satoru-takeuchi approved these changes
LGTM. Please squash commits.

2024-11-08 07:37 UTC, ushitora-anqou commented
@satoru-takeuchi I squashed my commits. Could you review this PR again?

2024-11-08 08:06 UTC, merged