stop using reader in MantleRestoreReconciler
cybozu-go/mantle pull request #71
Opened 2024-11-25 01:53 UTC by ushitora-anqou

2024-11-29 02:21 UTC, satoru-takeuchi requested changes

2024-11-29 02:21 UTC, satoru-takeuchi commented on internal/controller/mantlerestore_controller.go
>  		if errors.IsNotFound(err) {
It might cause resource leak. We might not delete the restoring PVC if this resoure is just created and is not on client cache. On the other hand, we don't want to remove the check of PVCAnnotationRestoredBy annotation. Do you have any good idea to resolve both problems? My ideas are as below.

1. Set ownerReference from the restoring PVC to the corresponding MantleRestore. We can do it because both resources are in the same namespace.
2. Deleting orphaned restoring PVC periodically.

2024-11-29 02:21 UTC, satoru-takeuchi commented on internal/controller/mantlerestore_controller.go
>  		if errors.IsNotFound(err) {
The same problem as deleteRestoringPV exists. Since we can't create ownerReference from PV to MantleRestore, my idea is just hand-made garbage collection as I described above.

2024-12-02 02:48 UTC, ushitora-anqou commented on internal/controller/mantlerestore_controller.go
> +			return fmt.Errorf("the restoring PV is already deleted: %s", pvName)
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/9416a07e9a447f1e661bcd8486180698c7bc834e.

2024-12-02 02:49 UTC, ushitora-anqou commented on internal/controller/mantlerestore_controller.go
>  // Note: it must use reader rather than client to check PVC existence to avoid oversighting a PV not in the cache.
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/b9d90c55cb6f9cf648aef878d94fe25252b47d38.

2024-12-02 02:49 UTC, ushitora-anqou commented on internal/controller/mantlerestore_controller.go
> +	if err := r.client.Get(ctx, client.ObjectKey{Name: pvcName, Namespace: pvcNamespace}, &pvc); err != nil {
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/b9d90c55cb6f9cf648aef878d94fe25252b47d38.

2024-12-02 02:49 UTC, ushitora-anqou commented on internal/controller/mantlerestore_controller.go
>  		if errors.IsNotFound(err) {
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/19901522bdfffdaafe3c0224aee628b14a316351.

2024-12-02 02:50 UTC, ushitora-anqou commented on internal/controller/mantlerestore_controller.go
>  		if errors.IsNotFound(err) {
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/44add37dad9f0410ff4dd66d97c0f657bc91aadd and https://github.com/cybozu-go/mantle/pull/71/commits/320f3050ba4b60634d1ef1d4e12b8812af5c647e.

2024-12-02 02:51 UTC, ushitora-anqou commented on test/e2e/singlek8s/restore_test.go
> -	It("should fail to delete the MantleRestore if failed to remove rbd image", func() {
NOTE: We discussed this and agreed to remove this test.

2024-12-02 04:33 UTC, ushitora-anqou commented
@satoru-takeuchi  I've fixed your points, so could you review this again?

2024-12-02 07:22 UTC, satoru-takeuchi commented on internal/controller/mantlerestore_controller.go
>  		if errors.IsNotFound(err) {
@ushitora-anqou Could you add a check to verify the existence of owner reference in `testCreateRestoringPVC`?

2024-12-02 08:05 UTC, satoru-takeuchi requested changes
I reviewed changed besides `garbage_collector_runner_test.go`.

2024-12-03 00:49 UTC, satoru-takeuchi requested changes

2024-12-03 00:49 UTC, satoru-takeuchi commented on internal/controller/garbage_collector_runner_test.go
> +	})
IMO, this test code looks a bit hard to maintain because of the following reasons.

- There are many function parameters.
- The meaning of functions (`make*` and `build*`) are ambiguous.

So, how about simplify code like this?

```suggestion
			func(
				ctx SpecContext,
				existMR bool,
				pvModifier func(pv *corev1.PersistentVolume),
				expectError, expectDeleted bool,
			) {
				runner := NewGarbageCollectorRunner(k8sClient, 1*time.Second)
				ns := resMgr.CreateNamespace()
				var mr mantlev1.MantleRestore
				mr.SetName("mr")
				mr.SetNamespace("ns")
				mr.Spec.Backup = "dummy"

				var pv corev1.PersistentVolume
				pv.SetAnnotations(map[string]string{
					PVAnnotationRestoredBy:          string(mr.GetUID()),
					PVAnnotationRestoredByName:      mr.GetName(),
					PVAnnotationRestoredByNamespace: mr.Getnamespace(),
				})

				if existMR {
					err = k8sClient.Create(ctx, mr)
					Expect(err).NotTo(HaveOccurred())
					err = k8sClient.Get(ctx, types.NamespacedName{Name: mr.GetName(), Namespace: mr.GetNamespace()}, mr)
					Expect(err).NotTo(HaveOccurred())
				}

				if pvModifier {
					pvModifier(&pv)
				}

				deleted, err := runner.isMantleRestoreAlreadyDeleted(ctx, pv)
				if expectError {
					Expect(err).To(HaveOccurred())
				} else {
					Expect(err).NotTo(HaveOccurred())
				}
				Expect(deleted).To(Equal(expectDeleted))
			}

		DescribeTable("isMantleRestoreAlreadyDeleted",
			doTest,
			Entry("MantleRestore exists", true, func false, false),
			Entry("MantleRestore does NOT exist", nil, false, true),
			Entry(
				"MantleRestore exists, but the PV's annotation has unexpected MR's UID",
				true,
				func(pv *corev1.PersistentVolume) {
					pv.Annotations[PVAnnotationRestoredBy] = "unexpected-uid"
				},
				false, true,
			),
			Entry(
				"PV annotation of restored-by missing",
				makeMR,
				func(pv *corev1.PersistentVolume) {
					delete(pv.Annotations, PVAnnotationRestoredBy)
				},
				true, false,
			),
			Entry(
				"PV annotation of restored-by-name missing",
				makeMR,
				func(pv *corev1.PersistentVolume) {
					delete(pv.Annotations, PVAnnotationRestoredByName)
				},
				true, false,
			),
			Entry(
				"PV annotation of restored-by-namespace missing",
				makeMR,
				func(pv *corev1.PersistentVolume) {
					delete(pv.Annotations, PVAnnotationRestoredByNamespace)
				},
				true, false,
			),
		)
	})
```

2024-12-03 00:49 UTC, satoru-takeuchi commented on internal/controller/garbage_collector_runner.go
> +	}
We should also check `pv.Spec.CSI.VolumeAttributes["clusterID"] is what this mantle controller manages.`

2024-12-03 04:24 UTC, ushitora-anqou commented on internal/controller/mantlerestore_controller.go
>  		if errors.IsNotFound(err) {
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/000a3f36f12d44e46de367d98d66e49737e5901f.

2024-12-03 04:24 UTC, ushitora-anqou commented on cmd/controller/main.go
> +	flags.StringVar(&gcInterval, "gc-interval", "1h", "The time period between each garbage collection.")
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:26 UTC, ushitora-anqou commented on cmd/controller/main.go
> +	}
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +		if err := r.deleteOrphanPVs(ctx); err != nil {
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +			logger.Error(err, "failed to delete orphan PVs", "error", err)
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +func (r *GarbageCollectorRunner) deleteOrphanPVs(ctx context.Context) error {
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +		logger.Info("an orphan PV is removed", "name", pv.GetName())
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +		return false, fmt.Errorf("failed to find annotation: %s", PVAnnotationRestoredBy)
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +		return false, fmt.Errorf("failed to find annotation: %s", PVAnnotationRestoredByName)
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +		return false, fmt.Errorf("failed to find annotation: %s", PVAnnotationRestoredByNamespace)
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +			return false, fmt.Errorf("failed to get MantleRestore: %w", err)
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner_test.go
> +		It("should remove only orphan PVs", func(ctx SpecContext) {
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner_test.go
> +			// No MantleRestore exists for pv2, so pv2 is orphan and should be removed.
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:27 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner_test.go
> +			err = runner.deleteOrphanPVs(ctx)
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:28 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner_test.go
> +			// Create PV pv1 for mr1
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:28 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner_test.go
> +			// Create PV pv2
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/743a3c5329b2552df61991e3a252f7375f9082ab.

2024-12-03 04:29 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +	}
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/77e054f372b07e6313a294495f3a833a7ebad1a0.

2024-12-03 04:30 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner_test.go
> +	})
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/00a64381266cef55b25dc7ec5fe04c3b7a3e60ff.

2024-12-03 04:30 UTC, ushitora-anqou commented
The last commit ([8571fe8](https://github.com/cybozu-go/mantle/pull/71/commits/8571fe8ad66749aaa7bf633d771d2476aec03c8a)) is just a _kaizen_.

2024-12-03 05:14 UTC, satoru-takeuchi requested changes
Almost looks good to me. I have last two change requests.

2024-12-03 05:14 UTC, satoru-takeuchi commented on internal/controller/garbage_collector_runner.go
> +		return false, fmt.Errorf("PV is not managed by target Ceph cluster: %s: %s", clusterID, r.managedCephClusterID)
This is not an error case.

```suggestion
		return false, nil
```

2024-12-03 05:14 UTC, satoru-takeuchi commented on internal/controller/garbage_collector_runner_test.go
> +			),
Could you add one more test for the check of clusterID?

```suggestion
			),
			Entry(
				"cluster ID does not match",
				true,
				func(pv *corev1.PersistentVolume) {
					pv.Spec.CSI = &corev1.CSIPersistentVolumeSource{
						VolumeAttributes: map[string]string{"clusterID": "different-cluster"},
				}				},
				false, false,
			),
```

2024-12-03 05:25 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner.go
> +		return false, fmt.Errorf("PV is not managed by target Ceph cluster: %s: %s", clusterID, r.managedCephClusterID)
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/1d60ebc98f03f7ac21ccc914788669e3a9cb1005.

2024-12-03 05:26 UTC, ushitora-anqou commented on internal/controller/garbage_collector_runner_test.go
> +			),
Fixed in https://github.com/cybozu-go/mantle/pull/71/commits/1d60ebc98f03f7ac21ccc914788669e3a9cb1005.

2024-12-03 05:29 UTC, satoru-takeuchi approved these changes
LGTM. Please squash commits once the CI has passed.

2024-12-04 01:59 UTC, ushitora-anqou commented
@satoru-takeuchi I squashed my commits and the CI has finally passed. Could you review this again?

2024-12-04 02:12 UTC, merged