support http(s) proxy
cybozu-go/mantle pull request #77
Opened 2024-12-06 02:34 UTC by ushitora-anqou

2024-12-09 06:10 UTC, satoru-takeuchi requested changes

2024-12-10 02:56 UTC, ushitora-anqou commented on internal/controller/mantlerestore_controller_test.go
> +		// Check the cache is new and the created PV can be fetched.
Fixed in https://github.com/cybozu-go/mantle/pull/77/commits/adb3ce512eb716fc410dc00c326a13dace63c683.

2024-12-10 03:03 UTC, ushitora-anqou commented
@satoru-takeuchi Could you review this PR again?

2024-12-10 04:03 UTC, satoru-takeuchi approved these changes
LGTM. Please squash commits.

2024-12-10 04:40 UTC, ushitora-anqou commented
@satoru-takeuchi I've squashed my commits. Could you review this PR again?

2024-12-10 04:40 UTC, satoru-takeuchi approved these changes

2024-12-10 04:41 UTC, merged