enhance tests
cybozu-go/mantle pull request #81
Opened 2024-12-23 02:32 UTC by ushitora-anqou

2025-01-06 23:57 UTC, satoru-takeuchi requested changes

2025-01-06 23:57 UTC, satoru-takeuchi commented on test/e2e/multik8s/suite_test.go
> +	By(fmt.Sprintf("%s: %s: checking MantleRestore correctly restores the replicated backups in both clusters",
Shouldn't this line be unnecessary or should be before L237?

2025-01-06 23:57 UTC, satoru-takeuchi commented on test/e2e/multik8s/suite_test.go
> +func ensureTemporaryResourcesRemoved(ctx context.Context) {
```suggestion
func ensureTemporaryResourcesDeleted(ctx context.Context) {
```

In k8s context, `delete` is more appropriate than `remove`.

2025-01-06 23:57 UTC, satoru-takeuchi commented on test/e2e/multik8s/suite_test.go
> +			strings.HasPrefix(n, "mantle-upload-")
Could you define string constants like `mantleExportJobPrefix = "mantle-export-" for mantle related jobs? It's to avoid to pass this tests even though resources are not deleted yet if there is a typo. For instance,  if "mantle-export-" is typed "mantle-exports-" by mistake, `strings.HasPrefix(n, "mantle-export-")` always returns `false`.

Since this is a minor cleanup, fixing in another PR is also OK.

2025-01-06 23:57 UTC, satoru-takeuchi commented on test/e2e/multik8s/suite_test.go
> +		return strings.HasPrefix(n, "mantle-discard-")
I guess the names of temporary PVs are not prefixed by "mantle-discard-". These PVs are dynamically created by ceph-csi and their names are prefixed by "pvc-".

IMO, the deletion of PVs are in charge of not mantle but K8s. So we can skip this check in this test.

2025-01-06 23:57 UTC, satoru-takeuchi commented on test/e2e/multik8s/suite_test.go
> +		It("should back up correctly if previous MB is removed in the secondary cluster", func(ctx SpecContext) {
```suggestion
		It("should back up correctly if previous MB is deleted in the secondary cluster", func(ctx SpecContext) {
```

2025-01-06 23:57 UTC, satoru-takeuchi commented on test/e2e/multik8s/suite_test.go
> +		It("should back up correctly if previous MB is removed in the primary cluster", func(ctx SpecContext) {
```suggestion
		It("should back up correctly if previous MB is deleted in the primary cluster", func(ctx SpecContext) {
```

2025-01-07 02:13 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +		return strings.HasPrefix(n, "mantle-discard-")
I'm afraid that PVs used by discard Jobs are provisioned statically, so their names have the common prefix.
cf. https://github.com/cybozu-go/mantle/blob/b086293750e9a6d791eeb653971b5dfbef5ea0e3/internal/controller/mantlebackup_controller.go#L1596

We can demonstrate it by running multik8s tests and watching `kubectl get pv -w`:

```
$ make -C test/e2e minikube-profile-secondary 
...
✅  minikube profile was successfully set to profile2
...

$ kubectl get pv -w
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                        STORAGECLASS      VOLUMEATTRIBUTESCLASS   REASON   AGE
...
mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e   1Gi        RWO            Retain           Pending                                                    <unset>                          0s
mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e   1Gi        RWO            Retain           Available                                                  <unset>                          0s
mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e   1Gi        RWO            Retain           Available   rook-ceph/mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e                     <unset>                          0s
mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e   1Gi        RWO            Retain           Bound       rook-ceph/mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e                     <unset>                          0s
mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e   1Gi        RWO            Retain           Terminating   rook-ceph/mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e                     <unset>                          27s
mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e   1Gi        RWO            Retain           Terminating   rook-ceph/mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e                     <unset>                          27s
mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e   1Gi        RWO            Retain           Terminating   rook-ceph/mantle-discard-f081c4da-3bdf-4468-95b7-9741fd43d81e                     <unset>                          27s
...
```

2025-01-07 03:10 UTC, satoru-takeuchi commented on test/e2e/multik8s/suite_test.go
> +		return strings.HasPrefix(n, "mantle-discard-")
Ah, OK. Got it.

2025-01-07 04:07 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +			err := changeClusterRole(primaryK8sCluster, roleStandalone)
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/dc7c89fa2f8820caf1ad8099e41c0df26d935530

2025-01-07 04:07 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +			By("changing the primary K8s cluster to standalone")
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/add4fa4561a51fcdec2488737b393f687b9290fc.

2025-01-07 04:07 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +			By("changing the secondary K8s cluster to standalone")
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/add4fa4561a51fcdec2488737b393f687b9290fc.

2025-01-07 04:07 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +		It("should delete MantleBackup in the primary cluster", func(ctx SpecContext) {
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/3cb74fcddd31104d3c0dc7ee4b5cb9943bced7b8.

2025-01-07 04:07 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +		It("should NOT delete MantleBackup in the secondary cluster", func(ctx SpecContext) {
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/3cb74fcddd31104d3c0dc7ee4b5cb9943bced7b8.

2025-01-07 04:08 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +	By(fmt.Sprintf("%s: %s: checking MantleRestore correctly restores the replicated backups in both clusters",
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/2e5749487f121e764b306f8af32db913c1741230.

2025-01-07 04:08 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +func ensureTemporaryResourcesRemoved(ctx context.Context) {
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/88a6ddb64e123ada38b03c8e665f8c470a82df3b.

2025-01-07 04:08 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +			strings.HasPrefix(n, "mantle-upload-")
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/5779066bb4948b87584f34c558d1259c05be9bde.

2025-01-07 04:09 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +		It("should back up correctly if previous MB is removed in the secondary cluster", func(ctx SpecContext) {
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/caec10f0bac1c9b4c716676fee51e2b5f6bb50ef.

2025-01-07 04:09 UTC, ushitora-anqou commented on test/e2e/multik8s/suite_test.go
> +		It("should back up correctly if previous MB is removed in the primary cluster", func(ctx SpecContext) {
Fixed in https://github.com/cybozu-go/mantle/pull/81/commits/014ecb01cd9bc1d56303bcfd88e096a574c93e3f.

2025-01-07 04:11 UTC, satoru-takeuchi approved these changes
LGTM. Please squash commits.

2025-01-07 06:43 UTC, ushitora-anqou commented
@satoru-takeuchi I squashed my commits. Could you review this again?

2025-01-07 06:44 UTC, satoru-takeuchi approved these changes

2025-01-07 06:44 UTC, merged